---
-
  become: true
  hosts: app
  name: "Deploy App"
  tasks:
    -
      git:
        dest: /home/ubuntu/reddit
        repo: "https://github.com/express42/reddit.git"
        version: monolith
      name: "Fetch the latest version of application code"
      notify: "restart puma"
    -
      bundler:
        chdir: /home/ubuntu/reddit
        state: present
      name: "bundle install"
