---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
  - name: Install ruby and rubygems and required packages
    apt:
      update_cache: yes
      pkg:
      - ruby-full
      - ruby-bundler
      - build-essential
